StarterSet/force-app/main/default/objects/ValidationObject__c/ValidationObject__c.object-meta.xml
<CustomObject>
    <label>Validation Object</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>ValidationObject</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StarterSet/force-app/main/default/objects/ValidationObject__c/fields/DmlException__c.field-meta.xml
<CustomField>
    <fullName>DmlException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This item raises a DmlException.</description>
    <inlineHelpText>This item raises a DmlException.</inlineHelpText>
    <label>DmlException</label>
    <type>Checkbox</type>
</CustomField>

StarterSet/force-app/main/default/objects/ValidationObject__c/fields/QueryException__c.field-meta.xml
<CustomField>
    <fullName>QueryException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This item raises a QueryException.</description>
    <inlineHelpText>This item raises a QueryException.</inlineHelpText>
    <label>QueryException</label>
    <type>Checkbox</type>
</CustomField>

StarterSet/force-app/main/default/classes/ValidationObjectHandler.cls
/**
 * Exception notification handler
 * @author Nakano Shoki
 */
public without sharing class ValidationObjectHandler
    extends BaseHandler {
    /**
     * @description Before insert
     * @author Nakano Shoki
     */
    public override void beforeInsert(List<sObject> newObjectList) {
        List<ValidationObject__c> validationObjectList = (List<ValidationObject__c>)newObjectList;
        for(ValidationObject__c validationObject : validationObjectList) {
            commonProcessing(validationObject);
        }
    }
    /**
     * @description Before update
     * @author Nakano Shoki
     */
    public override void beforeUpdate(Map<Id, sObject> newObjectMap, Map<Id, sObject> oldObjectMap) {
        Map<Id, ValidationObject__c> validationObjectMap = (Map<Id, ValidationObject__c>)newObjectMap;
        for(ValidationObject__c validationObject : validationObjectMap.values()) {
            commonProcessing(validationObject);
        }
    }
    /**
     * @description Raises a QueryException.
     * @author Nakano Shoki
     */
    public void commonProcessing(ValidationObject__c vo) {
        if(vo.DmlException__c) {
            Account a = new Account();
            insert a;
        }
        if(vo.QueryException__c) {
            for(Integer i = 0; i < 300; i++) {
                Account acc = [SELECT Id FROM Account LIMIT1];
            }
        }
    }
}