StarterSet/force-app/main/default/objects/ViewHistory__c/ViewHistory__c.object-meta.xml
<CustomObject>
    <label>参照履歴</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>参照履歴</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StarterSet/force-app/main/default/objects/ViewHistory__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <label>閲覧回数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

StarterSet/force-app/main/default/objects/ViewHistory__c/fields/ViewRecordId__c.field-meta.xml
<CustomField>
    <fullName>ViewRecordId__c</fullName>
    <label>参照したレコードID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/ViewHistory__c/fields/ViewUser__c.field-meta.xml
<CustomField>
    <fullName>ViewUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>参照ユーザ</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ViewHistorys</relationshipName>
    <type>Lookup</type>
</CustomField>

StarterSet/force-app/main/default/classes/CountNumberView.cls
public with sharing class CountNumberView extends Base{
    //-------------------------------------------------------
    // Variables & Constants
    //-------------------------------------------------------
    public CountNumberView() {
        // none
    }
    //-------------------------------------------------------
    // Processing part
    //-------------------------------------------------------
    /**
     * @description test
     * @param String recordId
     * @author Nakano Shoki
     */
    @AuraEnabled(cacheable=false)
    public static ViewHistory__c getViewHistory(String recordId) {
        try {
            List<ViewHistory__c> vh = [
                SELECT Id,
                       ViewUser__c,
                       ViewRecordId__c,
                       ViewCount__c
                FROM   ViewHistory__c
                WHERE  ViewRecordId__c = :recordId
                  AND  ViewUser__c = :UserInfo.getUserId()
                LIMIT 1
            ];
            if(vh.size() != 0) {
                return vh[0];
            } else {
                return new ViewHistory__c();
            }
        } catch (Exception e) {
            exceptionHandler(e);
            return new ViewHistory__c();
        }
    }
}