DX/dev/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>イベント</label>
    <nameField>
        <label>イベント名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DX/dev/force-app/main/default/objects/Event__c/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>開催日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

DX/dev/force-app/main/default/objects/Event__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>会計</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DX/dev/force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>参加者</label>
    <nameField>
        <label>参加者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DX/dev/force-app/main/default/objects/Participant__c/fields/Cup__c.field-meta.xml
<CustomField>
    <fullName>Cup__c</fullName>
    <label>杯数</label>
    <summarizedField>Record__c.Cup__c</summarizedField>
    <summaryForeignKey>Record__c.ParticipantId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

DX/dev/force-app/main/default/objects/Participant__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>イベント</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>参加者</relationshipLabel>
    <relationshipName>EventDRYo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DX/dev/force-app/main/default/objects/Participant__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>支払額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DX/dev/force-app/main/default/objects/Participant__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>CASE(Cup__c,
    0, ScoreBeforeCumulative__c,
    1, ScoreBeforeCumulative__c,
    2, ScoreBeforeCumulative__c,
    3, ScoreBeforeCumulative__c * 0.7,
    4, ScoreBeforeCumulative__c * 0.7,
       ScoreBeforeCumulative__c * 0.5
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>得点</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DX/dev/force-app/main/default/objects/Participant__c/fields/ScoreBeforeCumulative__c.field-meta.xml
<CustomField>
    <fullName>ScoreBeforeCumulative__c</fullName>
    <label>計算前の得点</label>
    <summarizedField>Record__c.Point__c</summarizedField>
    <summaryForeignKey>Record__c.ParticipantId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

DX/dev/force-app/main/default/classes/NonController.cls
public class NonController {
    @AuraEnabled
    public static ResponseDto getEvent() {
        ResponseDto res;
        try {
            List<Event__c> events = [SELECT   Id,
                                              Name
                                     FROM     Event__c
                                     ORDER BY EventDate__c DESC];
            res = new ResponseDto(true);
            res.value.put('events', events);
        } catch(Exception e) {
            res = new ResponseDto(false);
            // エラー文言をComponentに返したい場合は以下
            // res = new ResponseDto(false, 'Componentに返したいエラー文言' + e.getMessage());
        }
        return res;
    }
    @AuraEnabled
    public static ResponseDto getParticipant(Id eventId) {
        ResponseDto res;
        try {
            List<Participant__c> participants = [SELECT   Name,
                                                          Score__c,
                                                          Cup__c,
                                                          Payment__c,
                                                          ScoreBeforeCumulative__c
                                                 FROM     Participant__c
                                                 WHERE    EventId__c = :eventId
                                                 ORDER BY Score__c DESC];
            res = new ResponseDto(true);
            res.value.put('participants', participants);
        } catch(Exception e) {
            res = new ResponseDto(false);
            // エラー文言をComponentに返したい場合は以下
            // res = new ResponseDto(false, 'Componentに返したいエラー文言' + e.getMessage());
        }
        return res;
    }
}