StarterSet/force-app/main/default/objects/BulletinBoard__c/BulletinBoard__c.object-meta.xml
<CustomObject>
    <label>掲示板</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000000}</displayFormat>
        <label>掲示板</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/BodyText__c.field-meta.xml
<CustomField>
    <fullName>BodyText__c</fullName>
    <label>本文</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/IsAllowExternalPublish__c.field-meta.xml
<CustomField>
    <fullName>IsAllowExternalPublish__c</fullName>
    <defaultValue>false</defaultValue>
    <description>プロセスビルダーにて制御</description>
    <inlineHelpText>公開日を過ぎている AND 外部公開が許可されている場合 TRUE</inlineHelpText>
    <label>IsAllowExternalPublish</label>
    <type>Checkbox</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/IsAllowInternalPublish__c.field-meta.xml
<CustomField>
    <fullName>IsAllowInternalPublish__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsAllowInternalPublish</label>
    <type>Checkbox</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/NoticePostingPeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePostingPeriod__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <inlineHelpText>お知らせ掲載期間が過ぎたレコードはお知らせ画面に表示されなくなります。</inlineHelpText>
    <label>お知らせ掲載期間</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/PublicationOrder__c.field-meta.xml
<CustomField>
    <fullName>PublicationOrder__c</fullName>
    <defaultValue>99</defaultValue>
    <inlineHelpText>お知らせに表示される順を制御します。
お知らせの掲載順は、「掲載順」の次に「公開日」が評価されます。
(掲載順が同一で公開日が異なる場合、公開日が近いレコードが上位に表示される)</inlineHelpText>
    <label>掲載順</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/PublishDate__c.field-meta.xml
<CustomField>
    <fullName>PublishDate__c</fullName>
    <label>公開日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>件名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>タグ</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>ToDo</fullName>
            </value>
            <value>
                <fullName>カレンダー</fullName>
            </value>
            <value>
                <fullName>キャンペーン</fullName>
            </value>
            <value>
                <fullName>キャンペーンメンバー</fullName>
            </value>
            <value>
                <fullName>ケース</fullName>
            </value>
            <value>
                <fullName>コミュニティ</fullName>
            </value>
            <value>
                <fullName>ファイル</fullName>
            </value>
            <value>
                <fullName>プロファイル</fullName>
            </value>
            <value>
                <fullName>ホーム</fullName>
            </value>
            <value>
                <fullName>ユーザ</fullName>
            </value>
            <value>
                <fullName>リード</fullName>
            </value>
            <value>
                <fullName>活動</fullName>
            </value>
            <value>
                <fullName>契約</fullName>
            </value>
            <value>
                <fullName>権限セット</fullName>
            </value>
            <value>
                <fullName>行動</fullName>
            </value>
            <value>
                <fullName>取引先</fullName>
            </value>
            <value>
                <fullName>取引先責任者</fullName>
            </value>
            <value>
                <fullName>商談</fullName>
            </value>
            <value>
                <fullName>商品</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

StarterSet/force-app/main/default/objects/BulletinBoard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>種別</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>お知らせ</fullName>
            </value>
            <value>
                <fullName>機能紹介</fullName>
            </value>
            <value>
                <fullName>バージョンアップ</fullName>
            </value>
            <value>
                <fullName>メンテナンス</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

StarterSet/force-app/main/default/classes/BulletinBoardController.cls
/**
 * BulletinBoardController
 * @author Nakano Shoki
 */
public with sharing class BulletinBoardController {
    //-------------------------------------------------------
    // Variables & Constants
    //-------------------------------------------------------
    // public BulletinBoardController() {}
    //-------------------------------------------------------
    // Processing part
    //-------------------------------------------------------
    /**
     * @description test
     * @param none
     * @author Nakano Shoki
     */
    @AuraEnabled(cacheable=true)
    public static List<BulletinBoard__c> getBBType() {
        String userType = UserInfo.getUserType();
        String soql =
            ' SELECT Type__c' +
            ' FROM   BulletinBoard__c';
        if(userType == 'Standard') {
            soql += ' WHERE  IsAllowInternalPublish__c = true';
        } else {
            soql += ' WHERE  IsAllowExternalPublish__c = true';
        }
        soql += ' WITH   SECURITY_ENFORCED' +
                ' GROUP BY Type__c' +
                ' ORDER BY Type__c';
        return Database.query(soql);
    }
    /**
     * @description test
     * @param none
     * @author Nakano Shoki
     */
    @AuraEnabled(cacheable=true)
    public static List<BulletinBoard__c> getBBData() {
        String userType = UserInfo.getUserType();
        String soql =
            ' SELECT Id,' +
            '        Name,' +
            '        Subject__c,' +
            '        BodyText__c,' +
            '        Type__c,' +
            '        Tag__c,' +
            '        PublishDate__c,' +
            '        LastModifiedDate' +
            ' FROM   BulletinBoard__c';
        if(userType == 'Standard') {
            soql += ' WHERE  IsAllowInternalPublish__c = true';
        } else {
            soql += ' WHERE  IsAllowExternalPublish__c = true';
        }
        soql += ' WITH   SECURITY_ENFORCED' +
                ' ORDER BY PublicationOrder__c,' +
                '          PublishDate__c DESC,' +
                '          CreatedDate DESC';
        return Database.query(soql);
    }
    /**
     * @description test
     * @param none
     * @author Nakano Shoki
     */
    @AuraEnabled(cacheable=true)
    public static List<BulletinBoard__c> getImportantBBData() {
        String userType = UserInfo.getUserType();
        Datetime now = system.now();
        String soql =
            ' SELECT Id,' +
            '        Name,' +
            '        Subject__c,' +
            '        BodyText__c,' +
            '        Type__c,' +
            '        Tag__c,' +
            '        PublishDate__c,' +
            '        LastModifiedDate' +
            ' FROM   BulletinBoard__c';
        if(userType == 'Standard') {
            soql += ' WHERE  IsAllowInternalPublish__c = true';
        } else {
            soql += ' WHERE  IsAllowExternalPublish__c = true';
        }
        soql += '   AND  NoticePostingPeriod__c > :now' +
                ' WITH   SECURITY_ENFORCED' +
                ' ORDER BY PublicationOrder__c,' +
                '          PublishDate__c DESC,' +
                '          CreatedDate DESC';
        return Database.query(soql);
    }
    /**
     * @description test
     * @param none
     * @author Nakano Shoki
     */
    @AuraEnabled(cacheable=false)
    public static List<BulletinBoard__c> getBBDataSosl(String keyword, List<String> types) {
        // String.escapeSingleQuotes(keyword)
        String userType = UserInfo.getUserType();
        String sosl =
            ' FIND :keyword IN ALL FIELDS';
        sosl += ' RETURNING' +
                '     BulletinBoard__c(Id, Name, Subject__c, BodyText__c, Type__c, Tag__c, PublishDate__c, LastModifiedDate)';
        if(userType == 'Standard') {
            sosl += ' WHERE  IsAllowInternalPublish__c = true';
        } else {
            sosl += ' WHERE  IsAllowExternalPublish__c = true';
        }
        sosl += ' WITH   SECURITY_ENFORCED' +
                ' ORDER BY PublicationOrder__c,' +
                '          PublishDate__c DESC,' +
                '          CreatedDate DESC' +
                ' LIMIT 2000';
        List<List <sObject>> searchList = search.query(sosl);
        return (List<BulletinBoard__c>)searchList[0];
    }
}