DX/dev/force-app/main/default/objects/ApexCustomLog__c/ApexCustomLog__c.object-meta.xml
<CustomObject>
    <label>ApexCustomLog</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>ApexCustomLog</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DX/dev/force-app/main/default/objects/ApexCustomLog__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>LogLevel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DX/dev/force-app/main/default/objects/CustomObject1__e/CustomObject1__e.object-meta.xml
<CustomObject>
    <label>プラットフォームイベント</label>
</CustomObject>

DX/dev/force-app/main/default/classes/Error.cls
public class Error {
    public void test() {
        try {
            User u = new user();
            insert u;
        } catch(Exception e){
            CustomObject1__e newsEvent = new CustomObject1__e(
                Location__c='Mountain City');
            Database.SaveResult sr = EventBus.publish(newsEvent);
            ApexCustomLog__c acl = new ApexCustomLog__c();
            acl.LogLevel__c = 'ERROR';
        }
    }
}