DX/dev/force-app/main/default/objects/ApexCustomLog__c/ApexCustomLog__c.object-meta.xml
<CustomObject>
    <label>ApexCustomLog</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>ApexCustomLog</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DX/dev/force-app/main/default/objects/ApexCustomLog__c/fields/ExecutionUser__c.field-meta.xml
<CustomField>
    <fullName>ExecutionUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ExecutionUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApexCustomLog</relationshipName>
    <type>Lookup</type>
</CustomField>

DX/dev/force-app/main/default/objects/ApexCustomLog__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>LogLevel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DX/dev/force-app/main/default/objects/ApexCustomLog__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>LogMessage</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

DX/dev/force-app/main/default/objects/ExceptionHandler__e/ExceptionHandler__e.object-meta.xml
<CustomObject>
    <description>Exception発生時にログを保存するための一時保存用プラットフォームイベント</description>
    <label>ExceptionHandler</label>
</CustomObject>

StarterSet/force-app/main/default/objects/ExceptionHandler__e/fields/ExecutionUserID__c.field-meta.xml
<CustomField>
    <fullName>ExecutionUserID__c</fullName>
    <label>ExecutionUserID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/ExceptionHandler__e/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>TypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DX/dev/force-app/main/default/classes/ExceptionHandlerHandler.cls
public with sharing class ExceptionHandlerHandler extends BaseHandler {
    public override void processAfterInsert(List<Object> newObjects){
        List<ApexCustomLog__c> acList = new List<ApexCustomLog__c>();
        for(Object newObject : newObjects) {
            ExceptionHandler__e eh = (ExceptionHandler__e)newObject;
            ApexCustomLog__c ac = new ApexCustomLog__c(
                LogLevel__c = 'ERROR',
                ExecutionUser__c = eh.ExecutionUserID__c,
                TypeName__c = eh.TypeName__c,
                StackTrace__c = eh.StackTrace__c,
                LogMessage__c = eh.Message__c
            );
            acList.add(ac);
        }
        insert acList;
    }
}