StarterSet/force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>処理中で発生したExceptionのログを保持するためのクラス。
ExceptionNotification(プラットフォームイベント)のTrigger処理によって作成される。</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StarterSet/force-app/main/default/objects/ErrorLog__c/fields/ExecutionUser__c.field-meta.xml
<CustomField>
    <fullName>ExecutionUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ExecutionUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ErrorLog_ExecutionUser</relationshipName>
    <type>Lookup</type>
</CustomField>

StarterSet/force-app/main/default/objects/ErrorLog__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

StarterSet/force-app/main/default/objects/ErrorLog__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DX/dev/force-app/main/default/objects/ExceptionHandler__e/ExceptionHandler__e.object-meta.xml
<CustomObject>
    <description>Exception発生時にログを保存するための一時保存用プラットフォームイベント</description>
    <label>ExceptionHandler</label>
</CustomObject>

StarterSet/force-app/main/default/objects/ExceptionHandler__e/fields/ExecutionUserID__c.field-meta.xml
<CustomField>
    <fullName>ExecutionUserID__c</fullName>
    <label>ExecutionUserID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/ExceptionHandler__e/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>TypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/classes/ExceptionHandlerHandler.cls
public without sharing class ExceptionHandlerHandler extends BaseHandler {
    public override void processAfterInsert(List<Object> newObjects){
        List<ErrorLog__c> elList = new List<ErrorLog__c>();
        for(Object newObject : newObjects) {
            ExceptionHandler__e eh = (ExceptionHandler__e)newObject;
            ErrorLog__c el = new ErrorLog__c(
                ExecutionUser__c = eh.ExecutionUserID__c,
                TypeName__c = eh.TypeName__c,
                StackTrace__c = eh.StackTrace__c,
                LogMessage__c = eh.Message__c
            );
            elList.add(el);
        }
        insert elList;
    }
}