StarterSet/force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>処理中で発生したExceptionのログを保持するためのクラス。
ExceptionNotification(プラットフォームイベント)のTrigger処理によって作成される。</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StarterSet/force-app/main/default/objects/ErrorLog__c/fields/ExecutionUser__c.field-meta.xml
<CustomField>
    <fullName>ExecutionUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ExecutionUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ErrorLog_ExecutionUser</relationshipName>
    <type>Lookup</type>
</CustomField>

StarterSet/force-app/main/default/objects/ErrorLog__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

StarterSet/force-app/main/default/objects/ErrorLog__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/ExceptionNotification__e/ExceptionNotification__e.object-meta.xml
<CustomObject>
    <description>Exception発生時にログを保存するための一時保存用プラットフォームイベント</description>
    <label>ExceptionNotification</label>
</CustomObject>

StarterSet/force-app/main/default/objects/ExceptionNotification__e/fields/ExecutionUserID__c.field-meta.xml
<CustomField>
    <fullName>ExecutionUserID__c</fullName>
    <label>Execution User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/ExceptionNotification__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/objects/ExceptionNotification__e/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

StarterSet/force-app/main/default/classes/ExceptionNotificationHandler.cls
/**
 * Exception notification handler
 * @author Nakano Shoki
 */
public without sharing class ExceptionNotificationHandler extends BaseHandler {
    /**
     * @description After insert
     *      Save as an ErrorLog__c when an ExceptionNotification__e is created.
     * @author Nakano Shoki
     */
    public override void afterInsert(List<Object> newObjects) {
        List<ExceptionNotification__e> enList = (List<ExceptionNotification__e>)newObjects;
        List<ErrorLog__c> elList = new List<ErrorLog__c>();
        for(ExceptionNotification__e en : enList) {
            ErrorLog__c el = new ErrorLog__c(
                ExecutionUser__c = en.ExecutionUserID__c,
                TypeName__c = en.TypeName__c,
                StackTrace__c = en.StackTrace__c,
                LogMessage__c = en.Message__c
            );
            elList.add(el);
        }
        insert elList;
    }
}